/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef CONTSUM
#define CONTSUM

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class contSUM : public RooAbsPdf {
public:
  contSUM() {} ; 
  contSUM(const char *name, const char *title,
	      RooAbsReal& _dt,
	      RooAbsReal& _delta,
	      RooAbsReal& _taubkg,
	      RooAbsReal& _fp);
  contSUM(const contSUM& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new contSUM(*this,newname); }
  inline virtual ~contSUM() { }

protected:

  RooRealProxy dt ;
  RooRealProxy delta ;
  RooRealProxy taubkg ;
  RooRealProxy fp ;
  
  Double_t evaluate() const ;

private:

  ClassDef(contSUM,1) // Your description goes here...
};
 
#endif
