/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "contSUM.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(contSUM); 

 contSUM::contSUM(const char *name, const char *title, 
                        RooAbsReal& _dt,
                        RooAbsReal& _delta,
                        RooAbsReal& _taubkg,
                        RooAbsReal& _fp) :
   RooAbsPdf(name,title), 
   dt("dt","dt",this,_dt),
   delta("delta","delta",this,_delta),
   taubkg("taubkg","taubkg",this,_taubkg),
   fp("fp","fp",this,_fp)
 { 
 } 


 contSUM::contSUM(const contSUM& other, const char* name) :  
   RooAbsPdf(other,name), 
   dt("dt",this,other.dt),
   delta("delta",this,other.delta),
   taubkg("taubkg",this,other.taubkg),
   fp("fp",this,other.fp)
 { 
 } 



 Double_t contSUM::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return fp*delta+(1-fp)*exp(-abs(dt)/taubkg) ; 
 } 



