/***************************************************************************** 
 * Project: RooFit                                                           * 
 *                                                                           * 
 * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/ 

// Your description goes here... 

#include "Riostream.h" 

#include "DTbkg0.h" 
#include "RooAbsReal.h" 
#include "RooAbsCategory.h" 
#include <math.h> 
#include "TMath.h" 

ClassImp(DTbkg0); 

 DTbkg0::DTbkg0(const char *name, const char *title, 
                        RooAbsReal& _dt,
                        RooAbsReal& _tau,
                        RooAbsReal& _dw,
                        RooAbsReal& _w,
                        RooAbsCategory& _q) :
   RooAbsPdf(name,title), 
   dt("dt","dt",this,_dt),
   tau("tau","tau",this,_tau),
   dw("dw","dw",this,_dw),
   w("w","w",this,_w),
   q("q","q",this,_q)
 { 
 } 


 DTbkg0::DTbkg0(const DTbkg0& other, const char* name) :  
   RooAbsPdf(other,name), 
   dt("dt",this,other.dt),
   tau("tau",this,other.tau),
   dw("dw",this,other.dw),
   w("w",this,other.w),
   q("q",this,other.q)
 { 
 } 



 Double_t DTbkg0::evaluate() const 
 { 
   // ENTER EXPRESSION IN TERMS OF VARIABLE ARGUMENTS HERE 
   return exp(-abs(dt)/tau)*((1-q*dw)*w/2 + (1+q*dw)*(1-w)/2)/(4*tau) ; 
 } 



